# Generated by Django 3.2.12 on 2022-03-03 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta_and_inheritance', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='worker',
            index=models.Index(fields=['tab_num'], name='workers_tab_num_968d08_idx'),
        ),
    ]
