# Generated by Django 3.2.12 on 2022-03-03 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meta_and_inheritance', '0002_worker_workers_tab_num_968d08_idx'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderedWorker',
        ),
        migrations.CreateModel(
            name='OrderedWorker',
            fields=[
            ],
            options={
                'ordering': ['first_name', 'startwork_date'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('meta_and_inheritance.worker',),
        ),
    ]
