# Generated by Django 3.2.12 on 2022-03-03 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta_and_inheritance', '0003_auto_20220303_1346'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='worker',
            name='workers_tab_num_968d08_idx',
        ),
        migrations.AddIndex(
            model_name='worker',
            index=models.Index(condition=models.Q(('startwork_date__isnull', True), _negated=True), fields=['first_name', 'startwork_date'], name='idx_fname__startw_date__isnull'),
        ),
    ]
